# Generated by Django 4.1.4 on 2023-01-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=1000)),
                ('message', models.CharField(max_length=5000)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
