# Generated by Django 4.1.4 on 2022-12-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                ("banner", models.ImageField(upload_to="img/services")),
                ("description", models.CharField(max_length=200)),
            ],
            options={"verbose_name": "Service", "verbose_name_plural": "Services",},
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.CharField(max_length=300)),
                ("owner", models.CharField(max_length=20)),
                ("position", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
        migrations.CreateModel(
            name="ServiceCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("sideImage", models.ImageField(upload_to="img/serviceCards")),
                ("description", models.CharField(max_length=500)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.service",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "ServiceCard",
                "verbose_name_plural": "ServiceCards",
            },
        ),
    ]
