# Generated by Django 4.1.4 on 2022-12-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='description',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='comment',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='owner',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
