# Generated by Django 4.1.4 on 2023-01-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_description_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('sideImage', models.ImageField(upload_to='img/serviceDescription')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='')),
            ],
            options={
                'verbose_name': 'MainDescription',
                'verbose_name_plural': 'MainDescription',
            },
        ),
    ]
