# Generated by Django 4.1.4 on 2023-01-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_maindescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sideImage', models.ImageField(upload_to='img/SlidingImages')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.maindescription', verbose_name='')),
            ],
            options={
                'verbose_name': 'SlidingImage',
                'verbose_name_plural': 'SlidingImage',
            },
        ),
    ]
