# Generated by Django 4.1.4 on 2023-01-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_sidenotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidenotes',
            name='description',
            field=models.CharField(default='Image Description', max_length=1000),
        ),
    ]
