# Generated by Django 4.1.4 on 2023-01-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_sidenotes_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidenotes',
            name='service',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name=''),
            preserve_default=False,
        ),
    ]
