# Generated by Django 4.1.4 on 2023-01-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_sidenotes_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='company',
            field=models.CharField(default='', max_length=1502),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='priority',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.IntegerField(default=4),
        ),
    ]
