# Generated by Django 4.1.4 on 2023-01-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_testimonial_company_testimonial_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
    ]
