# Generated by Django 4.1.4 on 2023-01-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_testimonial_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='icon',
        ),
        migrations.AddField(
            model_name='servicecard',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
    ]
