# Generated by Django 4.1.4 on 2022-12-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientimages',
            name='client',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='tab_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='portfolioimages',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='slider',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='welcomingnote',
            name='bullet_list',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='welcomingnote',
            name='descriptive_text',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='welcomingnote',
            name='subheader',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='whychooseus',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
