# Generated by Django 4.1.4 on 2023-01-16 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_portfolioimages_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="tag",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolioimages",
            name="tag",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
