# Generated by Django 4.1.4 on 2023-01-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_portfolio_tag_portfolioimages_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='button_link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
