# Generated by Django 4.1.4 on 2023-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_slider_button_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='optionalId',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
