# Generated by Django 4.1.4 on 2023-01-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_slider_optionalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='optionalId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
