# Generated by Django 4.1.4 on 2022-12-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutIntro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.CharField(max_length=50)),
                ("subHeader", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=500)),
                ("service_list", models.CharField(max_length=500)),
                ("footNote", models.CharField(max_length=200)),
                ("sideImage", models.ImageField(upload_to="img/abt")),
            ],
            options={
                "verbose_name": "AboutIntro",
                "verbose_name_plural": "AboutIntros",
            },
        ),
        migrations.CreateModel(
            name="CompanyBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner", models.ImageField(upload_to="img/banners")),
            ],
            options={
                "verbose_name": "CompanyBanner",
                "verbose_name_plural": "CompanyBanners",
            },
        ),
        migrations.CreateModel(
            name="CompanyStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.CharField(max_length=100)),
                ("header", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "CompanyStatement",
                "verbose_name_plural": "CompanyStatements",
            },
        ),
    ]
