# Generated by Django 4.1.4 on 2022-12-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutintro',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutintro',
            name='footNote',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutintro',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutintro',
            name='service_list',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutintro',
            name='subHeader',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companystatement',
            name='description',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='companystatement',
            name='header',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companystatement',
            name='icon',
            field=models.CharField(max_length=1000),
        ),
    ]
