# Generated by Django 4.1.4 on 2023-01-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_aboutintro_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutintro',
            name='header',
            field=models.CharField(default='Seagate Electric Co Ltd', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutintro',
            name='subHeader',
            field=models.CharField(default='Our Story', max_length=150),
        ),
    ]
