# Generated by Django 4.1.4 on 2023-01-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutintro_header_alter_aboutintro_subheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutintro',
            name='mission',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutintro',
            name='values',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='aboutintro',
            name='vision',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
