# Generated by Django 4.1.4 on 2022-12-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toolImage", models.ImageField(upload_to="img/tools")),
                ("name", models.CharField(max_length=30)),
                ("small_desc", models.CharField(max_length=100)),
                ("big_desc", models.CharField(max_length=500)),
            ],
            options={"verbose_name": "Tool", "verbose_name_plural": "Tools",},
        ),
    ]
