# Generated by Django 4.1.4 on 2023-01-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_tool_big_desc_alter_tool_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='features',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='specification',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
    ]
