# Generated by Django 4.1.4 on 2023-01-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
    ]
